---
- name: Pull Kubernetes control plane images
  command: kubeadm config images pull --cri-socket=unix:///var/run/crio/crio.sock
  become: true

- name: Reset the Kubernetes master node
  command: kubeadm reset --cri-socket=unix:///var/run/crio/crio.sock
  become: true
  register: kubeadm_init


- name: Initialize the Kubernetes master node
  command: kubeadm init --cri-socket=unix:///var/run/crio/crio.sock
  become: true
  register: kubeadm_init
  changed_when: "'initialized' in kubeadm_init.stdout"

- name: Create .kube directory
  file:
    path: "{{ lookup('env', 'HOME') }}/.kube"
    state: directory
    mode: '0755'
  become: true

- name: Copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ lookup('env', 'HOME') }}/.kube/config"
    remote_src: yes
  become: true

- name: Change ownership of kube config
  file:
    path: "{{ lookup('env', 'HOME') }}/.kube/config"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: '0644'
  become: true

- name: Install Calico network plugin
  command: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.0/manifests/calico.yaml
  become: true
  environment:
    KUBECONFIG: "{{ lookup('env', 'HOME') }}/.kube/config"

- name: Generate join command
  command: kubeadm token create --print-join-command
  become: true
  register: join_command
  changed_when: false

- name: Save join command to file on master node
  copy:
    content: "{{ join_command.stdout }}"
    dest: /tmp/kubeadm_join_command.txt
  become: true

- name: Transfer join command file to worker node
  copy:
    src: /tmp/kubeadm_join_command.txt
    dest: /tmp/kubeadm_join_command.txt
  delegate_to: master_node_hostname
  become: true