# tasks/main.yaml

- name: Update apt package index
  apt:
    update_cache: yes

- name: Remove conflicting packages
  apt:
    name: "{{ conflicting_packages }}"
    state: absent

- name: Create directory for Docker keyrings
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  get_url:
    url: "{{ docker_gpg_key_url }}"
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker APT repository
  shell: |
    echo "{{ docker_apt_repo }}" | tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Update APT package index
  apt:
    update_cache: yes

- name: Install Docker packages
  apt: 
    name: "{{ docker_packages }}"
    state: present

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Debug Root user
  debug:
    msg: "Hello, {{ ansible_user }}"

- name: Ensure /etc/docker directory exists
  file:
    path: /etc/docker
    state: directory
    mode: '0755'

- name: Create /etc/docker/daemon.json with Docker daemon configuration
  copy:
    dest: /etc/docker/daemon.json
    content: "{{ docker_daemon_config }}"

- name: Enable Docker service
  systemd:
    name: docker
    enabled: yes

- name: Reload systemd daemon
  command: systemctl daemon-reload
  args:
    warn: false
