- hosts: all
  name: PlayBook to install docker and kubernetes
  become: yes
  become_method: sudo
  roles:
    - checkinstalls
    - dockeres
    - kubesetup

- name: Initialize Kubernetes on Master Node and Retrieve Join Command
  hosts: master
  become: true
  become_method: sudo
  roles:
    - cluster_setup


- name: Deploy with helm
  hosts: master
  become: true
  become_method: sudo
  roles:
    - helm_deploy


