---
- name: Perform pre-flight checks
  command: kubeadm reset --cri-socket unix:///var/run/crio/crio.sock
  become: true

- name: Retrieve the join command
  slurp:
    src: /tmp/kubeadm_join_command.txt
  register: join_command_file

- name: Decode join command
  set_fact:
    join_command: "{{ join_command_file['content'] | b64decode }}"

- name: Execute join command on worker node
  command: "{{ join_command.stdout }} --v=5"
  become: true
