---
- name: Add CRI-O repository GPG key
  become: true
  apt_key:
    url: https://pkgs.k8s.io/addons:/cri-o:/prerelease:/main/deb/Release.key
    state: present

- name: Add CRI-O repository
  become: true
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://pkgs.k8s.io/addons:/cri-o:/prerelease:/main/deb/
    state: present

- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Install CRI-O
  become: true
  apt:
    name: cri-o
    state: present
    
- name: Ensure CRI-O service is enabled and started
  become: true
  systemd:
    name: crio
    enabled: yes
    state: started
