---
- name: Add Kubernetes repository
  become: true
  copy:
    dest: /etc/apt/sources.list.d/kubernetes.list
    content: |
      deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /

- name: Add Kubernetes GPG key
  become: true
  apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key
    state: present

- name: Ensure specific versions of Kubernetes tools are installed
  become: true
  apt:
    name:
      - kubelet
      - kubectl=1.29.0-*
      - kubeadm
    state: present
    update_cache: yes

- name: Install jq
  become: true
  apt:
    name: jq
    state: present
    update_cache: yes

- name: Ensure kubelet service is enabled and started
  become: true
  systemd:
    name: kubelet
    enabled: yes
    state: started
