# ---
# - name:  Add Systemctl tasks
#   import_tasks: ./kubesetup/tasks/main.yml 

# - name:  Add Crio tasks
#   import_tasks: ./kubesetup/tasks/crio.yml 

# - name:  Add KubeSetup tasks
#   import_tasks: ./kubesetup/tasks/kube.yml 

---
- name: Ensure swap is off
  command: swapoff -a
  become: true

- name: Create k8s.conf for modules load
  become: true
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter

- name: Load kernel modules
  become: true
  modprobe:
    name: "{{ item }}"
  with_items:
    - overlay
    - br_netfilter

- name: Create k8s.conf for sysctl
  become: true
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1

- name: Apply sysctl params
  become: true
  command: sysctl --system

# Crio Tasks

- name: Add CRI-O GPG key
  become: true
  apt_key:
    url: https://pkgs.k8s.io/addons:/cri-o:/prerelease:/main/deb/Release.key
    state: present

- name: Add CRI-O repository
  become: true
  copy:
    dest: /etc/apt/sources.list.d/cri-o.list
    content: |
      deb [signed-by=/etc/apt/keyrings/cri-o-apt-keyring.gpg] https://pkgs.k8s.io/addons:/cri-o:/prerelease:/main/deb/ /

- name: Update apt and install CRI-O
  become: true
  apt:
    name: cri-o
    state: present
    update_cache: yes

- name: Ensure CRI-O service is enabled and started
  become: true
  systemd:
    name: crio
    enabled: yes
    state: started


#kubetasks

- name: Add Kubernetes GPG key
  become: true
  apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
    state: present

- name: Add Kubernetes repository
  become: true
  copy:
    dest: /etc/apt/sources.list.d/kubernetes.list
    content: |
      deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /

- name: Ensure specific versions of Kubernetes tools are installed
  become: true
  apt:
    name:
      - kubelet=1.29.0-*
      - kubectl=1.29.0-*
      - kubeadm=1.29.0-*
    state: present
    update_cache: yes

- name: Install jq
  become: true
  apt:
    name: jq
    state: present
    update_cache: yes

- name: Ensure kubelet service is enabled and started
  become: true
  systemd:
    name: kubelet
    enabled: yes
    state: started
