# tasks/main.yaml

- name: Ensure swap is off
  ansible.builtin.command:
    cmd: swapoff -a
  register: swapoff_result

- name: Comment out swap entry in /etc/fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#]*\s+swap\s+.*)$'
    replace: '#\1'

- name: Remount all filesystems
  ansible.builtin.command:
    cmd: mount -av
  register: mount_result

- name: Ensure required kernel modules are loaded
  ansible.builtin.copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      {% for module in k8s_kernel_modules %}
      {{ module }}
      {% endfor %}

- name: Load overlay module
  ansible.builtin.modprobe:
    name: overlay
    state: present

- name: Load br_netfilter module
  ansible.builtin.modprobe:
    name: br_netfilter
    state: present

- name: Ensure sysctl parameters are set for Kubernetes
  ansible.builtin.copy:
    dest: /etc/sysctl.d/k8s.conf
    content: "{{ k8s_sysctl_params }}"

- name: Apply sysctl parameters without reboot
  ansible.builtin.command:
    cmd: sysctl --system
  register: sysctl_result

- name: Add Kubernetes APT repository
  ansible.builtin.apt_repository:
    repo: "{{ k8s_apt_repo }}"
    filename: "kubernetes"

- name: Ensure /etc/apt/keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Kubernetes APT repository key
  get_url:
    url: "{{ k8s_apt_key_url }}"
    dest: "/usr/share/keyrings/kubernetes-archive-keyring.gpg"
    mode: '0644'

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Update apt and install Kubernetes tools
  apt:
    name: "{{ k8s_tools }}"
    state: present
    update_cache: yes

- name: Ensure kubelet service is enabled and started
  systemd:
    name: kubelet
    enabled: yes
    state: restarted

- name: Install additional packages
  apt:
    name: "{{ additional_packages }}"
    state: present
    update_cache: yes
