---
- name: Download Helm installation script
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0755'

- name: Install Helm
  shell: /tmp/get_helm.sh
  args:
    executable: /bin/bash

- name: Ensure helm is installed
  command: helm version
  register: helm_installed
  failed_when: helm_installed.rc != 0

- name: Add stable Helm repository
  community.kubernetes.helm_repository:
    name: stable
    repo_url: https://charts.helm.sh/stable
  when: helm_installed is succeeded

- name: Update Helm repositories
  community.kubernetes.helm_repository:
    name: stable
    repo_url: https://charts.helm.sh/stable
    state: present
  when: helm_installed is succeeded

- name: Deploy application using Helm chart
  community.kubernetes.helm:
    name: myapp
    chart_ref: stable/mychart
    release_namespace: default
  when: inventory_hostname == groups['master'][0]  