- name: Download get_helm.sh script
  ansible.builtin.get_url:
    url: "{{ helm_install_script_url }}"
    dest: /tmp/get_helm.sh
    mode: '0700'

- name: Install Helm
  ansible.builtin.command:
    cmd: /tmp/get_helm.sh

- name: Verify Helm installation
  ansible.builtin.command: helm version
  register: helm_version

- name: Display Helm version
  ansible.builtin.debug:
    msg: "{{ helm_version.stdout }}"

- name: Add helm repo
  kubernetes.core.helm_repository:
    name: "{{ helm_repo_name }}"
    repo_url: "{{ helm_repo_url }}"

- name: Install Nginx Chart
  kubernetes.core.helm:
    name: "{{ helm_chart_name }}"
    namespace: "{{ helm_chart_namespace }}"
    chart_ref: "{{ helm_chart_ref }}"
  environment:
    KUBECONFIG: "{{ ansible_user_dir }}/.kube/config"

- name: Gather information about nginx-server
  kubernetes.core.helm_info:
    name: "{{ helm_chart_name }}"
    release_namespace: "{{ helm_chart_namespace }}"
  environment:
    KUBECONFIG: "{{ ansible_user_dir }}/.kube/config"